config/routes.rb
Jaja::Application.routes.draw do
  root :to => "projects#index"

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects, :only => [:show] do
    resources :articles, only: [:show]
  end

  resources :articles, only: [:index]

  get 'tags/:tag', to: 'articles#index', as: :tag

  namespace :admin do
    resources :articles, only: [:index, :show]
    resources :projects do
      resources :articles, except: [:index, :show]
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :user_id, :project_id, :content, :title, :is_publish, :description, :tag_list
  acts_as_taggable

  belongs_to :user
  belongs_to :project

  scope :published, where(is_publish: true)
  scope :un_published, where(is_publish: false)

  def title_with_id
    array = []
    html = Markdown.parse(self.content)
    doc = Nokogiri::HTML(html)
    doc.xpath('//h2').each do |node|
      array << { node['id'] => node.text }
    end
    array
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :user_id, :description, :is_publish
  has_many :articles
  belongs_to :user

  scope :published, where(:is_publish => true)

  def title_with_id
    array = []
    html = Markdown.parse(self.description)
    doc = Nokogiri::HTML(html)
    doc.xpath('//h2').each do |node|
      array << { node['id'] => node.text }
    end
    array
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :username, :login
  # attr_accessible :title, :body
  attr_accessor :login

  has_many :projects
  has_many :articles

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/admin/articles_controller.rb
#encoding: utf-8
class Admin::ArticlesController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @article = @project.articles.build
  end

  def create
    @project = Project.find(params[:project_id])
    @article = @project.articles.build(params[:article])
    @article.user = current_user
    if @article.save
      flash[:notice] = "成功新增文章"
      redirect_to admin_article_path @article
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @article = @project.articles.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @article = @project.articles.find(params[:id])

    if @article.update_attributes(params[:article])
      flash[:notice] = "成功更新文章"
      redirect_to admin_article_path(@article)
    else
      render :edit
    end
  end

  def destroy
  end
end

app/controllers/admin/projects_controller.rb
#encoding: utf-8
class Admin::ProjectsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!

  def index
    @projects = Project.paginate(:page => params[:page])
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(params[:project])
    if @project.save
      flash[:notice] = "#{@project.name} 建立成功"
      redirect_to admin_project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "#{@project.name} 更新成功"
      redirect_to admin_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    name = @project.name
    @project.destroy

    flash[:notice] = "#{name} 刪除成功"
    redirect_to admin_projects_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_projects
  #before_filter :authenticate if Rails.env.production?

  protected

  def find_projects
    @all_projects = Project.published
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
       username == "jimmy" && password == "0975519929"
     end
  end

end

app/controllers/articles_controller.rb
#encoding: utf-8
class ArticlesController < ApplicationController
  def index
    if params[:tag]
      @tag = params[:tag]
      @articles = Article.tagged_with(@tag)
    else
      redirect_to projects_path
    end
  end
  def show
    @project = Project.published.find(params[:project_id])
    @article = @project.articles.find(params[:id])
    @page_title = @article.title
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "您要找的頁面並不存在"
    redirect_to "/"
  end
end

app/controllers/projects_controller.rb
#encoding: utf-8
class ProjectsController < ApplicationController

  def index
    @projects = Project.published.paginate(:page => params[:page])
  end

  def show
    @project = Project.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "您要找的頁面並不存在"
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.slim
= f.input :title, :label => "文章標題", :input_html => { :class => "span10" }
= f.input :description, label: "文章描述", input_html: { class: "span10" }, hint: "為了 SEO，首段不要超過 100 個中文字為佳，其中要包含標題中所有的關鍵字"
= f.input :content, :label => "內容", :input_html => { :class => "span10" }
= f.input :tag_list, :label => "標籤", :input_html => { :class => "span10" }, hint: "使用逗點間隔"
= f.input :is_publish, :as => :radio_buttons, :label => "是否公開", :item_wrapper_class => 'inline'
.form-actions
  = f.submit "儲存", :class => 'btn btn-primary'

app/views/admin/articles/edit.html.slim
h1 編輯 #{@article.title}
= simple_form_for(@article, url: admin_project_article_path(@article.project, @article), :html => { :class => 'form-horizontal' }) do |f|
  = render partial: 'form', locals: { f: f }

app/views/admin/articles/index.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            a.brand href="#" 文章列表
      #articles_wrapper
        table.table.table-striped.table-bordered.table-condensed
          thead
            tr
              th ID
              th 主題
              th 標題
              th 公開狀態
              th 建立時間
              th 編輯時間
              th 操作
          tbody
            - @articles.each do |article|
              tr
                td= article.id
                td= article.project.name
                td= article.title
                td= article.is_publish
                td= l article.created_at, :format => :short
                td= l article.updated_at, :format => :short
                td
                  = link_to project_article_path(article.project, article), :class => 'btn', :target => "_blank" do
                    = content_tag(:i, '', :class => 'icon icon-eye-open')
                    '  檢視
                  |
                  = link_to edit_admin_project_article_path(article.project, article), :class => 'btn' do
                    = content_tag(:i, '', :class => 'icon icon-edit')
                    '  編輯
      = will_paginate @articles

app/views/admin/articles/new.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            a.brand href="#" 新增文章
      #article_form
        = simple_form_for @article, url: admin_project_articles_path(@project), html: { class: 'form-horizontal' } do |f|
          = render :partial => 'form', locals: { f: f }

app/views/admin/articles/show.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            a.brand href="#" #{@article.title}
            ul.nav.pull-right
              li.divider-vertical
              li= link_to "編輯", edit_admin_project_article_path(@article.project, @article)
              li.divider-vertical
              li= link_to "顯示文章", project_article_path(@article.project, @article), :target => "_blank"
              li.divider-vertical
      #article
        span 發佈狀態：#{@article.is_publish?}
        = Markdown.parse @article.content
        #tags
          span = raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

app/views/admin/projects/_form.html.slim
= simple_form_for([:admin, @project], :html => { :class => 'form-horizontal' }) do |f|
  = f.input :name, :label => "主題名稱", :input_html => { :class => "span10" }
  = f.input :description, :label => "描述", :input_html => { :class => "span10" }
  = f.input :is_publish, :as => :radio_buttons, :label => "是否公開", :item_wrapper_class => 'inline'
  .form-actions
    = f.submit "儲存", :class => 'btn btn-primary'

app/views/admin/projects/edit.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 編輯 #{@project.name}
      #product_form
        = render :partial => 'form'

app/views/admin/projects/index.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" 主題列表
      #projects_wrapper
        table.table.table-striped.table-bordered.table-condensed
          thead
            tr
              th ID
              th 主題
              th 公開狀態
              th 建立時間
              th 編輯時間
              th 操作
          tbody
            - @projects.each do |project|
              tr
                td= project.id
                td= project.name
                td= project.is_publish
                td= l project.created_at, :format => :short
                td= l project.updated_at, :format => :short
                td
                  = link_to project_path(project), :class => 'btn', :target => "_blank" do
                    = content_tag(:i, '', :class => 'icon icon-eye-open')
                    '  檢視
                  |
                  = link_to edit_admin_project_path(project), :class => 'btn' do
                    = content_tag(:i, '', :class => 'icon icon-edit')
                    '  編輯
                  = link_to new_admin_project_article_path(project), :class => 'btn' do
                    = content_tag(:i, '', :class => 'icon icon-plus-sign')
                    '  新增文章
      = will_paginate @projects

app/views/admin/projects/new.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container
            a.brand href="#" 新增主題
      #product_form
        = render :partial => 'form'

app/views/admin/projects/show.html.slim
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container style="width: auto;"
            a.brand href="#" #{@project.name}
            ul.nav.pull-right
              li.divider-vertical
              li= link_to "編輯", edit_admin_project_path(@project)
              li.divider-vertical
              li= link_to "顯示文章", project_path(@project), :target => "_blank"
              li.divider-vertical
      #project
        = Markdown.parse @project.description

app/views/articles/index.html.slim
= render partial: "shared/meta_tag", locals: { title: "學習筆記", description: "分享學習過程中的心得" }

- content_for(:aside) do
  = render partial: 'shared/google_adsense'

header.page-header
  h1 搜尋標籤: #{@tag}
- @articles.each do |article|
  article
    .well
      header.hidden
        h1= link_to article.title, project_article_path(article.project, article)
      span
        | #{article.description[0..150] + "....."}
        | #{link_to "查看主題", project_article_path(article.project, article)}

app/views/articles/show.html.slim
= render partial: "shared/meta_tag", locals: { title: @article.title, description: @article.description }

- content_for(:aside) do
  = render partial: "shared/aside", locals: { subject: @article }

header.subhead#article-title
  h1= @article.title
section#article-content
  = Markdown.parse @article.content
section#tags
  = raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')
hr
- if Rails.env.production?
  section#comments
    #disqus_thread
      = raw disqus_thread

app/views/layouts/admin.html.slim
doctype html
html lang="zh"
head
  title #{t('brand')} | #{@title}
  = stylesheet_link_tag    "admin"
  = javascript_include_tag "admin"
  = csrf_meta_tags
  meta name="viewport" content="width=device-width" initial-scale="1.0"
  meta charset="UTF-8"
  body
    #maincontainer.no-sidebar
      #contentwrapper
        #contentcolumn
          /! ** blue top navbar **
          .blue.navbar.navbar-static.nomargin
            .navbar-inner
              .container
                a.brand href="#" JaJa
                ul.nav.pull-left
                  li
                    = link_to new_admin_project_path do
                      i.icon-xlarge.icon-cog
                      | 新增主題
                  li.divider-vertical
          .container-fluid
            .row-fluid
              .span12
                - if flash.any?
                  .c-alert.pillow-emboss
                    - flash.each do |name, msg|
                      div{class="alert-message #{name == :notice ? "info" : "error"}"}
                        a.close href="#"
                          i.icon-large.icon-remove-circle
                        = simple_format(msg)
                = yield
      #leftcolumn
        #leftpanel
          .leftpanel-wrapper
            ul.nav.nav-pills.nav-stacked
              li.user-container
                = link_to "主題列表", admin_projects_path
              li.user-container
                = link_to "文章列表", admin_articles_path
    .clearfix
    footer.footer

app/views/layouts/application.html.slim
DOCTYPE html
html lang="zh"
head
  = display_meta_tags site: "Jimmy 學習筆記"
  link href="https://plus.google.com/111185132903722481885/about" rel="author"
  /[ if lt IE 9 ]
    | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  = stylesheet_link_tag    "application"
  = javascript_include_tag "application"
  = render partial: 'shared/google_analytics' if Rails.env.production?
  = csrf_meta_tags
  meta name="viewport" content="width=device-width" initial-scale="1.0"
  meta charset="UTF-8"
body data-spy="scroll" data-target=".sidebar"
  .container
    header.role-header
      h1=link_to 'Jimmy 學習筆記', "/"
    / Navbar
    nav.navbar
      .navbar-inner
        .container
          h1.hidden-desktop.hidden-tablet.hidden-phone 主導覽
          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href='/' Jimmy 學習筆記
          .nav-collapse
            ul.nav
              - @all_projects.each do |project|
                li.dropdown
                  = link_to "#", id: "project-#{project.id}", class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button" do
                    | #{project.name}
                  - if project.articles.published.size != 0
                    ul.dropdown-menu role="menu" aria-labelledby="dLabel"
                      - project.articles.published.each do |article|
                        li= link_to article.title, project_article_path(project, article)
            - if current_user
              ul.nav.pull-right
                li= link_to "管理者後台", admin_projects_path, target: "_blank"
    .row
      .span9
        article
          = yield
      .span3
        = yield(:aside)
  footer
    .container
      = render "shared/footer"

app/views/projects/index.html.slim
= render partial: "shared/meta_tag", locals: { title: "學習筆記", description: "分享學習過程中的心得" }

- content_for(:aside) do
  = render partial: 'shared/google_adsense'

header.page-header.hidden-phone.hidden-tablet.hidden-desktop
  h1 筆記列表
- @all_projects.each do |project|
  article
    .well
      header.hidden
        h1= link_to project.name, project
      span
        | #{project.description[0..150] + "....."}
        | #{link_to "查看主題", project_path(project)}

app/views/projects/show.html.slim
= render partial: "shared/meta_tag", locals: { title: @project.name, description: @project.description }

- content_for(:aside) do
  = render partial: 'shared/aside', locals: { subject: @project }

header.page-header
  h1 #{@project.name}
section#project-description
  = Markdown.parse @project.description
section#articles
  header.page-header
    h1 #{@project.name} 的目錄
  ul
    - @project.articles.published.each do |article|
      li
        = link_to article.title, project_article_path(article.project, article), :class => 'hover-popover', "rel" => "popover", "data-trigger" => "hover", "data-content" => article.description, "data-title" => "摘要"
        ul
          - article.title_with_id.each do |t|
            li= link_to t.first.last, "##{t.first.first}"
blockquote
  p
    a href="http://gogojimmy.net" rel="author" gogojimmy
    '
    | 發表於:
    | <time datetime=#{l @project.updated_at, :format => "%Y-%m-%d %H:%M:%S"} pubdate>#{l @project.updated_at, :format => :short}</time>
hr
- if Rails.env.production?
  section#comments
    #disqus_thread
      = raw disqus_thread

app/views/shared/_aside.html.slim
ul.nav.nav-list
  - subject.title_with_id.each do |t|
    li= link_to "##{t.first.first}" do
      | #{t.first.last}
      i.icon-chevron-right.pull-right
= render partial: 'shared/google_adsense'

app/views/shared/_footer.html.slim
.row
  .span3
    a href="http://creativecommons.org/licenses/by-nc-sa/3.0/tw/deed.zh_TW" rel="license"
      img.cc alt="創用 CC 授權條款" src="http://i.creativecommons.org/l/by-nc-sa/3.0/tw/88x31.png" style="border-width:0"
    '
    span By gogojimmy.
  .span5
    ul.social
      li
        a href="https://plus.google.com/111185132903722481885?rel=author" About me
      li
        a href="http://twitter.com/gogojimmy"
          i.icon.icon-twitter-sign
      li
        a href="mailto:jimmy@gogojimmy.net"
          i.icon.icon-envelope-alt

app/views/shared/_meta_tag.html.slim
- set_meta_tags title: title , description: description
- set_meta_tags open_graph: { title: title,
                              description: "Article",
                              url: "#{request.protocol}#{request.host_with_port}#{request.fullpath}",
                              image: "http://graph.facebook.com/1589145634/picture?type=large" }